# Enable to get debug messages (where they are enabled)
debug: false

updater:
  # Set to true to enable updater checks.
  enabled: true
  # How fast should BungeeUtilisals check for new updates (in minutes)?
  # Set to -1 to disable repeating updater checks (differently said: setting this to -1 only checks for updates on startup)
  delay: 30
  # Set to true to automatically install updates on shutdown
  # Note that this automatic install may fail to install.
  install: false
  # Permission to get notified when an update has been found.
  permission: 'bungeeutilisals.updater.notify'

storage:
  # Possible storage types: MYSQL, POSTGRESQL, MARIADB, SQLITE, H2 & MONGODB | MySQL recommended
  # SQLite and H2 are for local, file, storage, these could (and likely will) slow down BungeeUtilisals for bigger networks.
  #
  # It's recommended to use MYSQL, POSTGRESQL or MARIADB for storage.
  type: 'H2'

  # The hostname (IP) to connect to
  hostname: '127.0.0.1'
  # Default ports:
  # MySQL / MariaDB: 3306, PostgreSQL: 5432, MongoDB: 27017
  port: 3306
  # The database / scheme name
  database: 'database'
  # The username, should at least have write & read access to the database above!
  username: 'username'
  # The password corresponding to the username above
  password: 'password'

  properties:
    serverTimezone: 'Europe/Brussels'
    characterEncoding: utf8
    # useSSL: true # uncomment this if SSL should be used

  pool:
    # How many connections are allowed to be made?
    # Find more information at:
    # https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
    max-pool-size: 5
    # How many idle connections should be maintained?
    min-idle: 3
    # Maximum lifetime of a connection. Time in seconds.
    max-lifetime: 300
    # How long should BungeeUtilisals wait before timing out a connection?
    connection-timeout: 8

  # Storage schema names
  schemas:
    users: 'bu_users'
    ignoredusers: 'bu_ignoredusers'
    friends: 'bu_friends'
    friendrequests: 'bu_friendrequests'
    friendsettings: 'bu_friendsettings'
    bans: 'bu_bans'
    mutes: 'bu_mutes'
    kicks: 'bu_kicks'
    warns: 'bu_warns'
    punishmentactions: 'bu_punishmentactions'
    reports: 'bu_reports'
    messagequeue: 'bu_messagequeue'