cache:
  paths:
    - .m2

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - master
  script:
    - mvn clean package install -Dmaven.repo.local=.m2/repository
  artifacts:
    name: "BungeeUtilisals"
    expire_in: 1 week
    paths:
      - bungee/target/BungeeUtilisals.jar