cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - master
  script:
    - mvn clean package install
  artifacts:
    name: "BungeeUtilisals"
    expire_in: 1 week
    paths:
      - target/*.jar