language: java
sudo: false
script: mvn clean verify install

services:
- docker
cache:
  directories:
  - "$HOME/.cache"

before_deploy:
- >
  if ! [ "$BEFORE_DEPLOY_RUN" ]; then
    export BEFORE_DEPLOY_RUN=1;
    git config --local user.name "didjee2";
    git config --local user.email "dieter08@live.be";
    export TRAVIS_TAG=${#$TRAVIS_JOB_ID - $TRAVIS_JOB_NUMBER};
    git tag $TRAVIS_TAG;
  fi

deploy:
- provider: releases
  api_key: $OAUTH_TOKEN
  file:
  - '/home/travis/build/didjee2/BungeeUtilisalsX/bungee/target/BungeeUtilisals.jar'
  skip_cleanup: true
  overwrite: true