# The length of the unique punishment id (only guaranteed to be unique per type, a puid of bans can be the same as the puid of mute)
# This punishment uid is mostly useful if you do not want to show a numeric id in the ban / mute message.
puid-length: 6

# The characters to be used for punishment uid's. It's recommended to leave this on the default setting.
puid-characters: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'

per-server-punishments: false