enabled: false

member-limits:
  - permission: bungeeutilisalsx.party.limits.default
    limit: 15
  - permission: bungeeutilisalsx.party.limits.vip
    limit: 25

inactivity-period:
  # How often should BungeeUtilisalsX scan for inactive parties (in seconds)?
  # This scans all parties for offline members, if all members are offline, the party will be flagged inactive.
  # Next scan, if the party is already inactive AND all party members are still offline, then the party will be removed.
  party: 60

  # How often should BungeeUtilisalsX scan for inactive party members (in seconds)?
  # This will flag members that are offline, next scan, if they are still offline, they will be removed from the party
  # If the party is empty, the party will be removed, if the party owner is offline, a new owner will be assigned automatically
  # Set this to -1 to not automatically remove inactive members!
  party-member: -1

command:
  aliases: 'party, bparty'
  permission: bungeeutilisalsx.party
  send-message: true
  # Set this to true to open gui on party command execute without arguments.
  open-gui: false

# Set this to false if you don't want people to be able to be invited if they are already in a party.
allow-invites-to-members-already-in-party: true

create:
  aliases: 'make, new'
  permission: bungeeutilisalsx.party.create

invite:
  aliases: 'invite, add'
  permission: bungeeutilisalsx.party.invite

accept:
  aliases: 'join'
  permission: bungeeutilisalsx.party.accept

leave:
  aliases: 'quit'
  permission: bungeeutilisalsx.party.leave

chat:
  aliases: 'c'
  permission: bungeeutilisalsx.party.chat

setowner:
  aliases: 'owner'
  permission: bungeeutilisalsx.party.setowner

kick:
  aliases: 'remove'
  permission: bungeeutilisalsx.party.kick