# Should the HubBalancer feature be enabled or not?
enabled: false

# Delay, in seconds, for the online ping task to be happening.
# This task checks if the lobbies listed below are online or not.
ping-delay: 10

# If false, hub balancing will be done based on player counts (supports redisbungee), if true, hub balancing will be random.
random: true

# Servers that will trigger the balancing, for example, if you fill in Lobby1, and the lobbies are set on Lobby1 & Lobby2
# The HubBalancer will then balance between Lobby1 and Lobby2 (random or based on count, see option above)
triggers:
  - Lobby1

lobbies:
  - Lobby1
  - Lobby2

# If an user gets kicked, he'll fallback to these servers.
fallback-servers:
  - Lobby1
  - Lobby2

fallback-trigger:
  # When using BLACKLIST, only kick reasons that contain what you add below will be kicked from the network.
  # When using WHITELIST, only kick reasons that DO NOT contain what you add below will be kicked from the network.
  type: 'BLACKLIST'
  reasons:
    - 'ban'
    - 'kick'

commands:
  hub:
    enabled: true
    aliases: 'lobby, gotohub'
    permission: bungeeutilisals.commands.hub