languages:
  en_US:
    # If default is true, this language will be default for new users, if false, users will be able to select it.
    default: true

# This checks the user's client language on first login.
# If the language is enabled in BungeeUtilisalsX, it will set the user's language to that.
check-default-language: true