# Should BungeeUtilisals use RedisBungee?
redis: false

# Currently this should only be enabled for AntiAFKAddon.
# This feature is highly experimental and might increase load on your server.
# This might also cause errors when newer versions come out, and BungeeUtilisals isn't updated yet.
packets: false

# Set to true to enable the use of addons ...
addons: false

updater:
  # Set to true to enable updater checks.
  enabled: true
  # How fast should BungeeUtilisals check for new updates (in minutes)?
  # Set to -1 to disable repeating updater checks (differently said: setting this to -1 only checks for updates on startup)
  delay: 30
  # Set to true to automatically install updates on shutdown
  # Note that this automatic install may fail to install.
  install: false
  # Permission to get notified when an update has been found.
  permission: 'bungeeutilisals.updater.notify'

# See: https://api.minetools.eu/uuid/
# This can be changed to any API you like, as long as the name / uuid is an URL parameter.
# The return type also MUST BE JSON + the json response MUST contain:
# - The "name" key for uuid to name convertion
# - The "id" key for name to uuid convertion (or uuid key if id key was not found).
#
# This should not be getting used often, at the time of writing (06/03/2019), it is only being used for the Importer tool.
urls:
  uuid-to-name: 'https://api.minetools.eu/uuid/'
  name-to-uuid: 'https://api.minetools.eu/uuid/'

storage:
  # Possible storage types: MYSQL, POSTGRESQL, MARIADB, SQLITE, MONGODB | MySQL recommended
  # SQLite is local storage, but WILL slow down BungeeUtilisals for bigger networks.
  type: 'MYSQL'

  # The hostname (IP) to connect to
  hostname: '127.0.0.1'
  # Default ports:
  # MySQL / MariaDB: 3306, PostgreSQL: 5432, MongoDB: 27017
  port: 3306
  # The database / scheme name
  database: 'database'
  # The username, should at least have write & read access to the database above!
  username: 'username'
  # The password corresponding to the username above
  password: 'password'
  # Should BungeeUtilisals try to establish a SSL connection? (only for SQL)
  useSSL: true

  pool:
    # How many connections are allowed to be made?
    # Find more information at:
    # https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
    max-pool-size: 5
    # How many idle connections should be maintained?
    # It is recommended to set this to the same value as the max-pool-size
    min-idle: 5
    # Maximum lifetime of a connection. Time in seconds.
    max-lifetime: 1500
    # How long should BungeeUtilisals wait before timing out a connection?
    connection-timeout: 8

  # Storage schema names
  schemas:
    users: 'bu_users'
    ignoredusers: 'bu_ignoredusers'
    friends: 'bu_friends'
    friendrequests: 'bu_friendrequests'
    friendsettings: 'bu_friendsettings'
    bans: 'bu_bans'
    mutes: 'bu_mutes'
    kicks: 'bu_kicks'
    warns: 'bu_warns'
    punishmentactions: 'bu_punishmentactions'