# Should BungeeUtilisals use RedisBungee?
redis: false

# Set to true to allow usage of things such as Bossbar, SimpleInventory, Movement registration, ...
# This might (and probably will) increase load on your servers (especially with addons using SimpleInventory or Movement packets enabled (f.e. AntiAFKAddon or FriendGUIAddon))
packets: false

# Set to true to enable the use of addons ...
addons: false

updater:
  # Set to true to enable updater checks.
  enabled: true
  # How fast should BungeeUtilisals check for new updates (in minutes)? Set to -1 to disable repeating updater checks.
  delay: 30
  # Set to true to automatically install updates on restart.
  install: false
  # Permission to get notified when an update has been found.
  permission: 'bungeeutilisals.updater.notify'

storage:
  # Possible storage types: MYSQL, POSTGRESQL, MARIADB, SQLITE, MONGODB | MySQL recommended
  # SQLite is local storage, but WILL slow down BungeeUtilisals for bigger networks.
  type: 'MYSQL'

  # The hostname (IP) to connect to
  hostname: '127.0.0.1'
  # Default ports:
  # MySQL / MariaDB: 3306, PostgreSQL: 5432, MongoDB: 27017
  port: 3306
  # The database / scheme name
  database: 'database'
  # The username, should at least have write & read access to the database above!
  username: 'username'
  # The password corresponding to the username above
  password: 'password'
  # Should BungeeUtilisals try to establish a SSL connection? (only for SQL)
  useSSL: true

  pool:
    # How many connections are allowed to be made?
    # Find more information at:
    # https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
    max-pool-size: 5
    # How many idle connections should be maintained?
    # It is recommended to set this to the same value as the max-pool-size
    min-idle: 5
    # Maximum lifetime of a connection. Time in seconds.
    max-lifetime: 1500
    # How long should BungeeUtilisals wait before timing out a connection?
    connection-timeout: 8

  # Storage schema names
  schemas:
    users: 'bu_users'
    friends: 'bu_friends'
    friendrequests: 'bu_friendrequests'
    friendsettings: 'bu_friendsettings'
    bans: 'bu_bans'
    ipbans: 'bu_ipbans'
    tempbans: 'bu_tempbans'
    iptempbans: 'bu_iptempbans'
    mutes: 'bu_mutes'
    ipmutes: 'bu_ipmutes'
    tempmutes: 'bu_tempmutes'
    iptempmutes: 'bu_iptempmutes'
    kicks: 'bu_kicks'
    warns: 'bu_warns'