name: Java CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
      - development
      - 162-bungee-gui
  pull_request:
    branches:
      - master
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      - name: Run tests with maven
        run: mvn test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      - name: Build with Maven
        run: bash build.sh -Dmaven.test.skip=true
      - name: Cache jar files
        uses: actions/cache@v2
        with:
          key: build-${{ github.sha }}
          path: |
            bungee/target/BungeeUtilisalsX*.jar
            velocity/target/BungeeUtilisalsX*.jar
            spigot/target/BungeeUtilisalsX*.jar
            webapi/target/BungeeUtilisalsX*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Cache jar files
        uses: actions/cache@v2
        with:
          key: build-${{ github.sha }}
          restore-keys: |
            build-
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: BungeeUtilisalsX
          retention-days: 14
          path: |
            bungee/target/BungeeUtilisalsX*.jar
            velocity/target/BungeeUtilisalsX*.jar
            spigot/target/BungeeUtilisalsX*.jar
            webapi/target/BungeeUtilisalsX*.jar