name: Remove old artifacts

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
      - development
      - 31-friends-gui
  pull_request:
    branches:
      - master
      - development
      - 31-friends-gui

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 month'
          skip-recent: 5